In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
df=pd.read_csv(r"C:\Users\KIIT0001\PycharmProjects\PythonProject\Heart\datasets_4123_6408_framingham.csv")

In [6]:
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [7]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [8]:
df.columns


Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [9]:
#since there is no use of education
df=df.drop(columns='education')
df.head()

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39              0         0.0     0.0                0   
1     0   46              0         0.0     0.0                0   
2     1   48              1        20.0     0.0                0   
3     0   61              1        30.0     0.0                0   
4     0   46              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [10]:
#continuous values are mostly filled with medium and ye/no onee is mode
bin_cols=["male","currentSmoker","prevalentStroke","prevalentHyp","diabetes"]

In [11]:
for col in bin_cols:
    model_val=df[col].mode()[0]
    df[col].fillna(model_val,inplace=True)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_17204\4252526481.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(model_val,inplace=True)
C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_17204\4252526481.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example

In [12]:
df.isnull().sum()

male                 0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [13]:
numeric_cols=["cigsPerDay","BPMeds","totChol","BMI","heartRate","glucose"]
for col in numeric_cols:
    medium_val=df[col].median()
    df[col].fillna(medium_val,inplace =True)

C:\Users\KIIT0001\AppData\Local\Temp\ipykernel_17204\1573528613.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(medium_val,inplace =True)


In [14]:
df.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [15]:
df["TenYearCHD"].value_counts()
#this shows imbalace so this can be bias\
# so we will use oversampling uner or whatever here we rae using oversamplking

TenYearCHD
0    3596
1     644
Name: count, dtype: int64

In [16]:
from sklearn .utils import resample
df_majority=df[df["TenYearCHD"]==0]
df_minority=df[df["TenYearCHD"]==1]
df_minority_upsampled=resample(df_minority,
                              replace=True,#sample with replacement(permanrent replace)
                              n_samples=len(df_majority),
                              random_state=42)
df_balanced=pd.concat([df_majority,df_minority_upsampled])

In [17]:
df_balanced["TenYearCHD"].value_counts()

TenYearCHD
0    3596
1    3596
Name: count, dtype: int64

In [18]:
#train-test-split

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [20]:
X=df_balanced.drop(columns=["TenYearCHD"])
y=df_balanced["TenYearCHD"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
X_train
# diaBP,totChol since these have great number so we have to scale
# as models will give importance t bade values not chote values

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
1905     0   64              0         0.0     0.0                0   
2075     0   37              1        20.0     0.0                0   
1128     0   63              1        10.0     0.0                0   
1782     0   65              0         0.0     0.0                0   
241      1   65              1        15.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
624      1   63              1        20.0     0.0                0   
485      1   54              1        40.0     0.0                0   
4232     1   68              0         0.0     0.0                0   
952      1   66              1        30.0     0.0                0   
1030     1   45              1        20.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
1905             1         0    229.0  145.0   85.0  29.67       70.0     74.0  
2075             0         0    166.0  112.0   73.5  21.64       75.0     93.0  
1128             1         0    236.0  189.0  103.0  27.91       60.0     74.0  
1782             1         0    245.0  171.0   89.0  23.07       82.0     93.0  
241              1         0    219.0  148.0   90.0  29.35       77.0     97.0  
...            ...       ...      ...    ...    ...    ...        ...      ...  
624              1         0    269.0  180.0  101.0  24.42       72.0     84.0  
485              0         0    230.0  145.0   90.0  25.72       75.0     85.0  
4232             1         0    176.0  168.0   97.0  23.14       60.0     79.0  
952              0         1    234.0  114.5   62.5  28.62       75.0    216.0  
1030             0         1    279.0  138.0   86.0  30.63       80.0    144.0  

[5753 rows x 14 columns]

In [22]:
#min-max and standard scaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)
X_test_scaled#this is numpy array..

array([[-0.97325535, -0.95932069,  0.98004615, ...,  0.50560704,
        -0.10921978,  0.7878483 ],
       [ 1.02747958, -0.15465441, -1.02036011, ..., -1.03763888,
         0.30156763, -0.40590413],
       [ 1.02747958,  0.65001186,  0.98004615, ..., -0.02587418,
        -1.17726704,  0.12075136],
       ...,
       [-0.97325535, -0.84436836, -1.02036011, ..., -1.08152265,
        -1.341582  , -0.19524194],
       [-0.97325535,  0.65001186,  0.98004615, ..., -0.23797907,
         1.53392985, -0.2303523 ],
       [-0.97325535,  0.07525024, -1.02036011, ..., -0.37694434,
        -1.50589697,  1.41983489]])

In [23]:
#Random forest
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier()
rf_model.fit(X_train_scaled,y_train)
y_pred=rf_model.predict(X_test_scaled)

In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [26]:
accuracy_score(y_test,y_pred)

0.9694232105628909

In [27]:
#Confusion matrix_
confusion_matrix(y_test,y_pred)

array([[696,  39],
       [  5, 699]])

In [28]:
print(classification_report(y_test,y_pred))#(what,internally how works,mathmatically )
# prdiction=TP/predicted yes
# recall=TP/actual yes
# error rate=FP+FN/total

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       735
           1       0.95      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439



In [29]:
!pip install xgboost



In [33]:

from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier

In [31]:
classifiers = [
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    SVC(),
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    GaussianNB(),
    XGBClassifier()
]

# Create a dictionary to store the results
results = {}


# Train and evaluate each classifier
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{clf_name} Accuracy: {accuracy}")
    
    # Classification report
    print(f"Classification Report for {clf_name}:")
    print(classification_report(y_test, y_pred))
    
    # Confusion matrix
    print(f"Confusion Matrix for {clf_name}:")
    print(confusion_matrix(y_test, y_pred))
    print("="*50)

RandomForestClassifier Accuracy: 0.9652536483669215
Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       735
           1       0.94      0.99      0.97       704

    accuracy                           0.97      1439
   macro avg       0.97      0.97      0.97      1439
weighted avg       0.97      0.97      0.97      1439

Confusion Matrix for RandomForestClassifier:
[[694  41]
 [  9 695]]
AdaBoostClassifier Accuracy: 0.6518415566365532
Classification Report for AdaBoostClassifier:
              precision    recall  f1-score   support

           0       0.68      0.60      0.64       735
           1       0.63      0.71      0.66       704

    accuracy                           0.65      1439
   macro avg       0.65      0.65      0.65      1439
weighted avg       0.65      0.65      0.65      1439

Confusion Matrix for AdaBoostClassifier:
[[441 294]
 [207 497]]
GradientBoostingCl

In [38]:
# Create a DataFrame to store the results
results_df = pd.DataFrame(columns=['Model', 'Accuracy', 'F1-Score', 'Precision', 'Recall'])

# Train and evaluate each classifier
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)
    
    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    f1_score = report['weighted avg']['f1-score']
    precision = report['weighted avg']['precision']
    recall = report['weighted avg']['recall']
    
    # Append results to DataFrame
    results_df = pd.concat(results_df,pd.DataFrame
                           ([{'Model': clf_name, 'Accuracy': accuracy, 'F1-Score': f1_score, 
                                    'Precision': precision, 'Recall': recall}, ignore_index=True

results_df

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid